### ISSUE TITLE
apoc.nlp.aws.entities.graph and apoc.nlp.aws.entities.stream not returning results or debug information

### ISSUE THREAD

**Issue by joedepeau** [neo4j/apoc#387]
Versions : Neo4j 5.5.0, apoc-5.5.0-extended.jar, apoc-nlp-dependencies-5.5.0-all.jar

Following the documentation, I created a test node and set parameters for my Access Key and Secret Key.

{
  "identity": 377257,
  "labels": [
    "test"
  ],
  "properties": {
    "id": 12,
    "body": "Flexible Data Models Provide Life-Saving Insights into Complex Cancer Research Data"
  },
  "elementId": "377257"
}

I tried calling the apoc.nlp.aws.entities.x functions, but I'm not getting any data returned and there's no additional debugging information shown.

MATCH (a:test {id: 12})
CALL apoc.nlp.aws.entities.graph(a, {
 key: $apiKey,
 secret: $apiSecret,
 nodeProperty: "body",
 writeRelationships: "ENTITY"
})
YIELD graph as g
RETURN g

MATCH (a:test {id: 12})
CALL apoc.nlp.aws.entities.stream(a, {
 key: $apiKey,
 secret: $apiSecret,
 nodeProperty: "body"
})
YIELD value
UNWIND value.entities AS entity
RETURN entity;

In the AWS console I can see that my keys were logged as being used for the Comprehend service, so I assume the API is being reached by APOC, but perhaps either the request or response format/requirements have changed and the APOC functions are no longer compatible?

**Comment by Lojjs** [comment]
@joedepeau Since the split between APOC core and extended in 5.0, this repo contains APOC core while APOC extended still lives here: https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues. As their are different team handling APOC core (Cypher Surface) and APOC extended (community/devrel), would you mind closing this issue and re-opening it in the other repo instead?
