### ISSUE TITLE
Docker usage documentation Inconsistency

### ISSUE THREAD

**Issue by solter** [neo4j/apoc#514]
The instructions for using docker in the [readme (line 227)](https://github.com/neo4j/apoc/blob/bbdafcb68d33fdae7a598c4d6ace56d877008c46/readme.adoc?plain=1#L227C2-L227C2) are different than the instructions in the official docs pages here: https://neo4j.com/docs/apoc/current/installation/#docker

These should be updated for consistency and accuracy. I believe the ones in the readme are accurate, whereas using the env variables as specified in the official docs result in the error:
> Failed to read config /var/lib/neo4j/conf/neo4j.conf: Setting 'apoc.export.file.enabled' for APOC was found in the configuration file. In Neo4j v5, APOC settings must be in their own configuration file called apoc.conf. Cleanup the config or disable 'server.config.strict_validation.enabled' to continue.

**Comment by gem-neo4j** [comment]
Hello :) Thanks for writing it. The official docs work on later versions of APOC, there was a bug in previous versions, which is why the README is different as it seems to have been missed in the update when the Docker commands were fixed, which version of APOC are you trying to load?

I can fix this up for consistency for sure :)
