### ISSUE TITLE
The `apoc.periodic.truncate` procedure doesn't provide a feedback if fails

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#57]
<a href="https://github.com/vga91"><img src="https://avatars.githubusercontent.com/u/25103389?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [vga91](https://github.com/vga91)**
_Wednesday Oct 27, 2021 at 12:26 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2266_

----

The `apoc.periodic.truncate` procedure doesn't provide a feedback if fails (for example if `dbms.memory.transaction.database_max_size` is reached) 

## Expected Behavior (Mandatory)

Should fails

## Actual Behavior (Mandatory)

Doesn't return nothing and doesn't cancel all db.

### Steps (Mandatory)

  1. Create a relatively big graph, for example `unwind range(0, 9999) as range create (:Node)-[:REL]->(:Other)`
  1. Set `dbms.memory.transaction.database_max_size=10M` in `neo4j.conf` and restart
  1. `CALL apoc.periodic.truncate`

### Versions

  - OS: Mac BigSur
  - Neo4j: 4.3.3
  - Neo4j-Apoc: 4.3.0.3

**Comment by hvub** [comment]
Related: https://github.com/neo4j/apoc/issues/56

In current versions of Neo4j (5.25.1) there is no `dbms.memory.transaction.database_max_size` option, cf. https://neo4j.com/docs/operations-manual/current/configuration/configuration-settings/

Please note — as pointed out https://github.com/neo4j/neo4j/issues/13097) — that "any local memory within a CALL is not counted towards the transaction memory limit due to current limitations in our procedure API". This may improve in the future.
