### ISSUE TITLE
Rebind for deletedNodes and deletedRelationships is disabled in the code

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#64]
<a href="https://github.com/magaton"><img src="https://avatars.githubusercontent.com/u/4103157?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [magaton](https://github.com/magaton)**
_Wednesday Nov 24, 2021 at 19:39 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/2375_

----

https://github.com/neo4j-contrib/neo4j-apoc-procedures/commit/80397b78d2edb3c991e24d9610bec13962a3bdd8#r60829647

**Comment by hvub** [comment]
Can any one elaborate what this issues is about? What is the problem/expectation w.r.t. APOC?

**Comment by gem-neo4j** [comment]
Hi! This is no longer commented in the code, and looks like it was fixed [here](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2899) :)

**Comment by gem-neo4j** [comment]
@hvub entities contain their own transaction, if you have found them in one transaction and want to access them in another, they need to be "rebound" otherwise when working with them, you will get errors as the old transaction is most likely closed. However, for this case, there seems to have been issues with rebinding deleted nodes based on which phase the trigger was on, so the person who fixed this makes sure to only rebind them in certain trigger phases (I haven't looked more into that part) :)
