### ISSUE TITLE
Cleanup apoc.meta.*TypeProperties()

### ISSUE THREAD

**Issue by neo-technology-build-agent** [neo4j/apoc#71]
<a href="https://github.com/SaschaPeukert"><img src="https://avatars.githubusercontent.com/u/6998439?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SaschaPeukert](https://github.com/SaschaPeukert)**
_Wednesday May 12, 2021 at 11:58 GMT_
_Originally opened as https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1903_

----

Currently, the code for apoc.meta.nodeTypeProperties() and apoc.meta.relTypeProperties() can use some cleanup. Bonus: APOC does not compile under windows thanks to encoding errors. Will tackle both of these issues with a PR.

**Comment by hvub** [comment]
According to the original issue https://github.com/neo4j-contrib/neo4j-apoc-procedures/issues/1903, the issue was addressed by this PR https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1904, which is merged since a long time. Only the original issue was never closed for unknown reasons. Probably just forgotten. It also seems the issue was created specifically for the PR (created on the same day). Hence, I consider this issue closed.
